-- Dynamic Barcode Management System: skema awal (PostgreSQL 13+).
-- Dijalankan otomatis oleh `npm run migrate` di dalam satu transaksi.

-- Ekstensi trigram untuk pencarian ILIKE '%teks%' yang cepat. Bersifat opsional:
-- jika ekstensi tidak tersedia/tidak boleh dibuat, aplikasi tetap berjalan (seq scan
-- pada 10.000 baris tetap hitungan milidetik).
DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS pg_trgm;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pg_trgm tidak tersedia (%): index trigram dilewati.', SQLERRM;
END
$$;

-- ---------------------------------------------------------------------------
-- users: akun admin
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                VARCHAR(120) NOT NULL,
  username            VARCHAR(50)  NOT NULL,
  email               VARCHAR(190) NOT NULL,
  password_hash       VARCHAR(255) NOT NULL,             -- bcrypt, tidak pernah plaintext
  role                VARCHAR(20)  NOT NULL DEFAULT 'admin',
  is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
  password_changed_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  last_login_at       TIMESTAMPTZ,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT users_role_check CHECK (role IN ('admin', 'viewer'))
);
CREATE UNIQUE INDEX users_username_uidx ON users (lower(username));
CREATE UNIQUE INDEX users_email_uidx    ON users (lower(email));

-- ---------------------------------------------------------------------------
-- import_batches: riwayat import CSV (ringkasan + baris yang gagal)
-- ---------------------------------------------------------------------------
CREATE TABLE import_batches (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename      VARCHAR(255),
  total_rows    INTEGER     NOT NULL DEFAULT 0,
  success_count INTEGER     NOT NULL DEFAULT 0,
  failed_count  INTEGER     NOT NULL DEFAULT 0,
  first_code    VARCHAR(32),
  last_code     VARCHAR(32),
  errors        JSONB       NOT NULL DEFAULT '[]'::jsonb,   -- [{row, reason, data}]
  created_by    BIGINT REFERENCES users (id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX import_batches_created_at_idx ON import_batches (created_at DESC);

-- ---------------------------------------------------------------------------
-- barcodes: satu baris = satu QR dinamis. QR hanya menyimpan URL /b/{code};
-- tujuan sebenarnya (target_url) bisa diubah kapan saja tanpa mengubah QR.
-- ---------------------------------------------------------------------------
CREATE SEQUENCE barcode_code_seq AS BIGINT START WITH 1 INCREMENT BY 1;

CREATE TABLE barcodes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR(32)  NOT NULL,
  name            VARCHAR(150) NOT NULL,
  description     TEXT,
  target_type     VARCHAR(20)  NOT NULL DEFAULT 'url',
  target_url      TEXT         NOT NULL,
  status          VARCHAR(10)  NOT NULL DEFAULT 'active',
  expired_at      TIMESTAMPTZ,
  scan_count      BIGINT       NOT NULL DEFAULT 0,
  last_scanned_at TIMESTAMPTZ,
  import_batch_id BIGINT REFERENCES import_batches (id) ON DELETE SET NULL,
  created_by      BIGINT REFERENCES users (id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT barcodes_status_check      CHECK (status IN ('active', 'inactive')),
  CONSTRAINT barcodes_target_type_check CHECK (target_type IN ('url', 'whatsapp', 'email', 'phone')),
  CONSTRAINT barcodes_target_len_check  CHECK (char_length(target_url) <= 2048),
  -- Pertahanan berlapis: walaupun validasi aplikasi terlewat, DB menolak javascript:, data:, dll.
  CONSTRAINT barcodes_target_scheme_check CHECK (target_url ~* '^(https?://|mailto:|tel:)')
) WITH (fillfactor = 80);   -- ruang kosong agar update counter scan bisa berupa HOT update

-- Kolom scan_count / last_scanned_at sengaja TIDAK di-index: dengan begitu update
-- counter pada setiap scan tidak perlu menyentuh index mana pun (HOT update).
CREATE UNIQUE INDEX barcodes_code_uidx           ON barcodes (code);
CREATE INDEX        barcodes_status_created_idx  ON barcodes (status, created_at DESC);
CREATE INDEX        barcodes_created_at_idx      ON barcodes (created_at DESC);
CREATE INDEX        barcodes_expired_at_idx      ON barcodes (expired_at) WHERE expired_at IS NOT NULL;
CREATE INDEX        barcodes_import_batch_idx    ON barcodes (import_batch_id) WHERE import_batch_id IS NOT NULL;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm') THEN
    CREATE INDEX barcodes_code_trgm_idx       ON barcodes USING gin (code       gin_trgm_ops);
    CREATE INDEX barcodes_name_trgm_idx       ON barcodes USING gin (name       gin_trgm_ops);
    CREATE INDEX barcodes_target_url_trgm_idx ON barcodes USING gin (target_url gin_trgm_ops);
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- barcode_history: riwayat perubahan URL tujuan
-- ---------------------------------------------------------------------------
CREATE TABLE barcode_history (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode_id BIGINT      NOT NULL REFERENCES barcodes (id) ON DELETE CASCADE,
  old_url    TEXT,
  new_url    TEXT        NOT NULL,
  changed_by BIGINT REFERENCES users (id) ON DELETE SET NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX barcode_history_barcode_idx    ON barcode_history (barcode_id, changed_at DESC);
CREATE INDEX barcode_history_changed_at_idx ON barcode_history (changed_at DESC);

-- ---------------------------------------------------------------------------
-- barcode_scans: log mentah setiap scan (append-only)
-- ---------------------------------------------------------------------------
CREATE TABLE barcode_scans (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barcode_id       BIGINT      NOT NULL REFERENCES barcodes (id) ON DELETE CASCADE,
  scanned_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  ip_address       INET,
  user_agent       VARCHAR(512),
  referer          VARCHAR(512),
  device           VARCHAR(20) NOT NULL DEFAULT 'unknown',
  browser          VARCHAR(40) NOT NULL DEFAULT 'Other',
  operating_system VARCHAR(40) NOT NULL DEFAULT 'Other'
);
CREATE INDEX barcode_scans_barcode_scanned_idx ON barcode_scans (barcode_id, scanned_at DESC);
CREATE INDEX barcode_scans_scanned_at_idx      ON barcode_scans (scanned_at);

-- ---------------------------------------------------------------------------
-- scan_stats_daily: rollup harian per barcode. Semua statistik dashboard dibaca
-- dari sini, sehingga tetap ringan walaupun barcode_scans berisi jutaan baris
-- (dan barcode_scans boleh dipangkas tanpa menghilangkan statistik).
-- Diperbarui atomik pada setiap scan dalam satu statement SQL.
-- ---------------------------------------------------------------------------
CREATE TABLE scan_stats_daily (
  barcode_id       BIGINT      NOT NULL REFERENCES barcodes (id) ON DELETE CASCADE,
  stat_date        DATE        NOT NULL,              -- tanggal lokal (APP_TIMEZONE)
  device           VARCHAR(20) NOT NULL,
  browser          VARCHAR(40) NOT NULL,
  operating_system VARCHAR(40) NOT NULL,
  scans            INTEGER     NOT NULL DEFAULT 0,
  PRIMARY KEY (barcode_id, stat_date, device, browser, operating_system)
) WITH (fillfactor = 80);
CREATE INDEX scan_stats_daily_date_idx ON scan_stats_daily (stat_date);

-- ---------------------------------------------------------------------------
-- user_sessions: penyimpanan session (connect-pg-simple)
-- ---------------------------------------------------------------------------
CREATE TABLE user_sessions (
  sid    VARCHAR      NOT NULL PRIMARY KEY,
  sess   JSON         NOT NULL,
  expire TIMESTAMP(6) NOT NULL
);
CREATE INDEX user_sessions_expire_idx ON user_sessions (expire);
