import { CSV_BOM, csvLine, parseCsv } from '../../lib/csv.js';
import { forbidden } from '../../lib/http-errors.js';
import { stripFormulaGuard, truncate } from '../../lib/text.js';
import * as barcodes from '../barcodes/barcodes.repo.js';
import { parseStatusWord, validateBarcodeInput } from '../barcodes/barcodes.validation.js';

const CHUNK_SIZE = 1000;
const MAX_STORED_CELL = 200;

/** Columns of the template file the admin can download. */
export const TEMPLATE_CSV = `${CSV_BOM}${csvLine(['name', 'description', 'target_url', 'status', 'expired_at'])}${[
  ['Menu Digital Warung Sate', 'Menu di meja pelanggan', 'https://example.com/menu/warung-sate', 'active', ''],
  ['Katalog Batik 2026', 'Brosur pameran', 'https://example.com/katalog/batik-2026', 'active', '31-12-2026'],
  ['Formulir Presensi Kuliah Umum', '', 'https://example.com/presensi', 'inactive', ''],
]
  .map((r) => csvLine(r))
  .join('')}`;

const short = (v) => truncate(String(v ?? ''), MAX_STORED_CELL);

/**
 * Imports barcodes from CSV. Valid rows are inserted (all in ONE transaction, in batches of 1000);
 * invalid rows are reported with the spreadsheet row number and the reason. Codes are generated by the
 * system: an import never lets the CSV decide a code.
 */
export async function runImport(ctx, { buffer, filename }, user) {
  if (user?.role !== 'admin') throw forbidden();
  const { db, config } = ctx;

  let parsed;
  try {
    parsed = parseCsv(buffer, { maxRows: config.imports.maxRows });
  } catch (err) {
    return { ok: false, error: err.message };
  }

  const missing = ['name', 'target_url'].filter((h) => !parsed.headers.includes(h));
  if (missing.length) {
    return {
      ok: false,
      error: `Kolom wajib tidak ditemukan: ${missing.join(', ')}. Kolom yang terbaca: ${parsed.headers.filter(Boolean).join(', ') || '(tidak ada)'}.`,
    };
  }

  const valid = [];
  const errors = [];
  let totalRows = 0;

  for (const { row, data } of parsed.rows) {
    if (Object.values(data).every((v) => String(v).trim() === '')) continue; // blank line
    totalRows += 1;

    const status = parseStatusWord(data.status);
    const { values, errors: fieldErrors } = validateBarcodeInput(
      {
        name: stripFormulaGuard(data.name ?? ''),
        description: stripFormulaGuard(data.description ?? ''),
        target_type: 'url',
        target_url: data.target_url ?? '',
        status: status ?? 'invalid',
        expired_at: data.expired_at ?? '',
      },
      { appOrigin: config.appOrigin, timezone: config.timezone },
      { allowedTypes: ['url'] },
    );
    if (status === null) fieldErrors.status = 'Status harus active/inactive (atau aktif/nonaktif).';

    const messages = Object.values(fieldErrors);
    if (messages.length) {
      errors.push({
        row,
        reason: messages.join(' '),
        data: { name: short(data.name), description: short(data.description), target_url: short(data.target_url), status: short(data.status), expired_at: short(data.expired_at) },
      });
    } else {
      valid.push(values);
    }
  }

  if (totalRows === 0) return { ok: false, error: 'File tidak berisi baris data.' };

  const batch = await db.tx(async (tx) => {
    const created = await tx.one(
      'INSERT INTO import_batches (filename, created_by) VALUES ($1, $2) RETURNING id',
      [truncate(filename || 'import.csv', 255), user.id],
    );

    let firstCode = null;
    let lastCode = null;
    for (let i = 0; i < valid.length; i += CHUNK_SIZE) {
      const inserted = await barcodes.insertRows(tx, config, valid.slice(i, i + CHUNK_SIZE), {
        createdBy: user.id,
        importBatchId: created.id,
      });
      if (config.codes.mode === 'sequential' && inserted.length) {
        // Sequential codes end in a number; compare numerically so BR-999999 < BR-1000000.
        const codes = inserted.map((r) => r.code).sort((a, b) => Number(a.split('-')[1]) - Number(b.split('-')[1]));
        firstCode ??= codes[0];
        lastCode = codes[codes.length - 1];
      }
    }

    return tx.one(
      `UPDATE import_batches SET total_rows = $2, success_count = $3, failed_count = $4,
              first_code = $5, last_code = $6, errors = $7::jsonb
       WHERE id = $1 RETURNING id, filename, total_rows, success_count, failed_count, first_code, last_code, created_at`,
      [created.id, totalRows, valid.length, errors.length, firstCode, lastCode, JSON.stringify(errors)],
    );
  });

  ctx.cache.clear();
  ctx.logger.info({ batchId: batch.id, ok: batch.success_count, failed: batch.failed_count, userId: user.id }, 'csv import finished');
  return { ok: true, batch };
}

export const getBatch = (db, id) =>
  db.one(
    `SELECT b.id, b.filename, b.total_rows, b.success_count, b.failed_count, b.first_code, b.last_code, b.created_at,
            u.username AS created_by_username
     FROM import_batches b LEFT JOIN users u ON u.id = b.created_by WHERE b.id = $1`,
    [id],
  );

export const recentBatches = (db, limit = 8) =>
  db.rows(
    `SELECT b.id, b.filename, b.total_rows, b.success_count, b.failed_count, b.created_at, u.username AS created_by_username
     FROM import_batches b LEFT JOIN users u ON u.id = b.created_by ORDER BY b.id DESC LIMIT $1`,
    [limit],
  );

/** One page of the failed rows of a batch (sliced in SQL: the JSON can hold thousands of entries). */
export const errorPage = (db, batchId, page, perPage) =>
  db.rows(
    `SELECT (e.value->>'row')::int AS row, e.value->>'reason' AS reason, e.value->'data' AS data
     FROM import_batches b, jsonb_array_elements(b.errors) WITH ORDINALITY AS e(value, n)
     WHERE b.id = $1 ORDER BY e.n OFFSET $2 LIMIT $3`,
    [batchId, (page - 1) * perPage, perPage],
  );

/** All failed rows as a CSV the admin can fix and upload again. */
export async function errorsCsv(db, batchId) {
  const rows = await db.rows(
    `SELECT (e.value->>'row')::int AS row, e.value->>'reason' AS reason, e.value->'data' AS data
     FROM import_batches b, jsonb_array_elements(b.errors) WITH ORDINALITY AS e(value, n)
     WHERE b.id = $1 ORDER BY e.n`,
    [batchId],
  );
  let out = CSV_BOM + csvLine(['row', 'reason', 'name', 'description', 'target_url', 'status', 'expired_at']);
  for (const r of rows) {
    out += csvLine([r.row, r.reason, r.data?.name, r.data?.description, r.data?.target_url, r.data?.status, r.data?.expired_at]);
  }
  return out;
}
