// Generates src/lib/icons.generated.js from the Phosphor "bold" set (MIT, @phosphor-icons/core).
// Only the icons listed below are extracted, so the app has no runtime dependency on the package.
//   npm run icons:build
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'node_modules', '@phosphor-icons', 'core', 'assets', 'bold');
const OUTPUT = path.join(ROOT, 'src', 'lib', 'icons.generated.js');

const ICONS = [
  'squares-four', 'qr-code', 'plus', 'plus-circle', 'upload-simple', 'download-simple', 'chart-line-up',
  'clock-counter-clockwise', 'gear-six', 'pencil-simple', 'trash', 'printer', 'eye', 'power', 'dots-three',
  'magnifying-glass', 'funnel', 'x', 'check', 'check-circle', 'warning', 'warning-circle', 'info',
  'arrow-right', 'arrow-up-right', 'arrow-left', 'caret-left', 'caret-right', 'caret-down', 'caret-up',
  'copy', 'sign-out', 'user', 'key', 'list', 'file-csv', 'link', 'device-mobile', 'desktop', 'globe',
  'whatsapp-logo', 'envelope-simple', 'phone', 'lightning', 'shield-check', 'chart-bar', 'stack', 'clock',
  'calendar-blank', 'arrow-counter-clockwise', 'x-circle', 'prohibit', 'hourglass', 'lock-simple',
  'database', 'cursor-click', 'table', 'arrows-down-up', 'file-arrow-down', 'plus-minus', 'browser',
  'robot', 'identification-card', 'minus', 'question', 'trend-up', 'trend-down', 'circle-notch',
];

const out = {};
const missing = [];
for (const name of ICONS) {
  try {
    const svg = await readFile(path.join(SOURCE_DIR, `${name}-bold.svg`), 'utf8');
    const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
    if (!inner) throw new Error('empty');
    out[name] = inner;
  } catch {
    missing.push(name);
  }
}
if (missing.length) {
  console.error(`Ikon tidak ditemukan: ${missing.join(', ')}`);
  process.exit(1);
}

const body = Object.entries(out)
  .map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`)
  .join('\n');

await mkdir(path.dirname(OUTPUT), { recursive: true });
await writeFile(
  OUTPUT,
  `// GENERATED by scripts/build-icons.js from Phosphor Icons (bold), MIT License, https://phosphoricons.com\n// Do not edit by hand.\nexport const ICONS = {\n${body}\n};\n`,
);
console.log(`Ditulis ${Object.keys(out).length} ikon ke ${path.relative(ROOT, OUTPUT)}`);
